### ISSUE TITLE
Remove some dependencies

### ISSUE THREAD

**Issue by nantonel** [kul-forbes/ProximalAlgorithms.jl#19]
Currently REQUIRE has RecursiveArrayTools and AbstractOperators as dependencies.

These however can be removed:
- [x]  **AbstractOperators** is solely due to the LBFGS. #18 should remove this.
- [x]  **RecursiveArrayTools** is due to the files contained in `utilities/tomove.jl` which extend `prox`, `gradient`  and their in-place versions to `ArrayPartition`s. If we move these to ProximalOperators then this dependency won't be necessary.
- [x] **Drop Julia 0.7** minor release required in version tag (i.e. v0.3.0)

**Comment by lostella** [comment]
Solved by #18
