### ISSUE TITLE
Question about reproting data

### ISSUE THREAD

**Issue by pylat** [kul-forbes/ProximalAlgorithms.jl#24]
I have a question about the Iteratortools module. I would like to apply the sampling method with different frequencies. Lets say I want to display results of an algorithm with frequency 100 (as you have with the verbose option), and save some variables of the algorithm every 10 iteration (for plotting). My current workaround is to do something like this 
  
    if report iter = tee(iter, fun) end
    if verbose iter = tee(sample(iter, freq), disp) end

where fun is saving the data if iteration number is divisible by 10. I am wondering if there a better way of doing this that I missed?

**Comment by lostella** [comment]
If you need more control over what happens during the iterations, you can always use a for loop like

```julia 
for (k, state) in enumerate(iter) # iter is your algorithm’s iterable
    if k % 10 == 0 save-the-state end
    if k % 100 == 0 print-the-state end
end
```

This might be easier in your case.
