### ISSUE TITLE
Tests on number of iterations are sensitive to randn

### ISSUE THREAD

**Issue by rfourquet** [kul-forbes/ProximalAlgorithms.jl#37]
A PkgEval run for a [PR](https://github.com/JuliaLang/julia/pull/35078) which changes the generated numbers for `randn!` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master). Apologies if this is a false positive.
cf. https://github.com/JuliaCI/NanosoldierReports/blob/7de24e455342298cbef56826b5827f0d7640d2c1/pkgeval/by_hash/b89e35c_vs_098ef24/logs/ProximalAlgorithms/1.5.0-DEV-71a4a114c2.log

**Comment by nantonel** [comment]
@lostella I remember we decided to relax the tests on the number of iterations (I couldn't find the issue though). 

Looks like they were not relaxed enough? The order look very similar, so it is definitively that:
```
[...]
  Expression: it_dys <= 1900
   Evaluated: 2363 <= 1900
[...]
  Expression: it_dys <= 2600
   Evaluated: 2877 <= 2600
[...]
  Expression: it_afba <= maxit
   Evaluated: 530 <= 500
```
I wonder if these tests could be replaced by something more robust...

**Comment by lostella** [comment]
@nantonel I think at this point it would be great to replace these tests with some fixed problem, instead of randomly generated...

**Comment by nantonel** [comment]
I see that most calls to `randn` don't use a fixed random generator like`randn(rng, ComplexF32, (2, 3))`. 

That should avoid pasting numbers like in [the LBFGS tests](https://github.com/kul-forbes/ProximalAlgorithms.jl/blob/master/test/accel/lbfgs.jl) unless random generators are changed which I don't think happen very often.

**Comment by lostella** [comment]
@nantonel #38 fixes this
