### ISSUE TITLE
pull request gone wrong

### ISSUE THREAD

**Issue by pylat** [kul-forbes/ProximalAlgorithms.jl#39]
Hi Lorenzo,
I was trying to open a pull request for an update on the stepsizes for the primal-dual solver, but I forgot to change my remote and ended up committing to the main ProximalAlgorithms repo. I subsequently reverted to your last commit. Sorry for that.

**Comment by lostella** [comment]
@pylat now worries, thanks for the heads up. We could “protect” the master branch against these issues, and make it impossible to push to master directly without a PR
