### ISSUE TITLE
Type stability on Iterators

### ISSUE THREAD

**Issue by nantonel** [kul-forbes/ProximalAlgorithms.jl#8]
In order to get type stable iterators we should specify the types of the fields of these objects.
For example the `FBSIterator` would become:
```julia
mutable struct FBSIterator{I <: Integer, R <: Real, 
                                        D <: BlockArray, C <: BlockArray, 
                                        FS, AS, FQ, AQ, G} <: ProximalAlgorithm{I, D}
    x::D
    fs::FS
    As::AS
    fq::FQ
    Aq::AQ
    g::G
    gamma::R
    maxit::I
    tol::R
...
``` 
Notice that I added also `C <: BlockArray`: this is because preallocated outputs coming from e.g. `Aq*x` 
can have different type with respect to `x`  (for example they might be complex).  

This gives a problem since the constructor of `FBSIterator` currently has `Aq=Identity(blocksize(x0))` in its keyword arguments. 
We should find a way to make sure that `Aq` and `As` are mapping to the same codomain / type.  

I think we should abandon `Identity` in favour of `Zeros` of `AbstractOperators`.  
The default key argument of  `Aq` and `As` would become:
```julia
Aq = Zeros(blockeltype(x0), blocksize(x0), blocksize(x0) )
``` 

Then we would need a utility function inside the constructors of the iterators that takes as inputs `Aq` and `As` and ensures these have the same codomain and domain. 
Moreover if either one of `Aq` or `As` is of type `Zeros` the function substitutes this with a new `Zeros` object that has consistent codomain with the operator that is not.

Alternatively we could allow for different codomain/types of `Aq` and `As` with `Cq` and `Cs`.

**Comment by lostella** [comment]
I think we should avoid over-specifying parametric type constraints in the iterators, and go for the simpler
```
mutable struct FBSIterator{I <: Integer, R <: Real, D, C, FS, AS, FQ, AQ, G} <: ProximalAlgorithm{I, D}
```
(specifying `Integer` and `Real` is fine, since they are basic Julia types).

The default for linear operators when should be (some type of) identity. Why zeros? I would try to fix `Identity` to ensure types are right (or somehow use the one from `AbstractOperators`: I don't remember why I ended up coding a new one, but I guess it was zero effort to overcome some limitation).

I agree that these points are important. The rest (checking types of domains and codomains of operators in constructors and so on) we can discuss but I guess it's less urgent: for now we should provide the right defaults (with right types and so on) and assume that when the user specifies something he does it the right way.

**Comment by nantonel** [comment]
Well I picked up `Zeros` because it has already what we need. 

While `Eye` (and `Identity`) are always need same codomain and domain
```julia
julia> Eye(10)
I  ℝ^10 -> ℝ^10 
```
with `Zeros` you don't have such constraint:
```
julia> Zeros(Float64,(10,10), Complex{Float64}, (2,))
0  ℝ^(10, 10) -> ℂ^2 
```

**Comment by lostella** [comment]
But the default operators should be identities (think of FBS and what you would want to obtain if you specify `fs` but not `As`), and as such have same input/output types, shapes and everything. 

Now that I think of it, there’s no problem *here*: the problem is how to infer `C` from the kw arguments (`D` is inferred by `x0`).

**Comment by nantonel** [comment]
well that could be possible by adding the following lines of code inside the constructor of the iterator:
```julia
Asx = blockzeros(codomainType(Asx),size(As,1)) #preallocate As*x
Cs = typeof(Asx)
```

I think in the end the best thing to do is to keep both `Cs` and `Cq`. 

This requires to extend `codomainType` to matrices:
```julia
codomainType(A::M) where {T, M <: AbstractMatrix{T}} = T
```
I think this should belong to `AbstractOperators` however.

**Comment by lostella** [comment]
True, there's `Cs` and `Cq` in the case of `FBS` (and similar algorithms). But I wouldn't rush the following:

> I think this should belong to `AbstractOperators` however

Maybe we should first work a solution out inside `ProximalAlgorithms`, and then figure out the best way to go. This way one can change the solution locally without having to go through the hell of cross-package version bumping.

**Comment by lostella** [comment]
Also, I don't think that for `AbstractMatrix` that definition of `codomainType` really works. We should probably reason *jointly* in terms of `T`, the type of the matrix coefficients, and `D` (the type of the stuff going into the operator). For example, if `T = Float64` and `D = `Complex{Float64}`, then the result of applying the operator will also be `Complex{Float64}`.

**Comment by nantonel** [comment]
yes this is true... I think we had such discussion when implementing `AbstractOperators.MatrixOp`. This thing should be fixed also there, because currently it gets the codomain and domain types form the matrix type!

**Comment by nantonel** [comment]
I think in the end the best thing could be to leave the choice of the codomain type of the operator to the user. Otherwise you need either to create objects or increase the dependencies to `AbstractOperators`. 

Here is a test of how the `FBSIterator` constructor could look like:
```julia
function FBSIterator(x0::D;
                     fs::FS=Zero(), As::AS=Identity(x0),
                     fq::FQ=Zero(), Aq::AQ=Identity(x0),
                     g::G=Zero(), gamma::R=-1.0, maxit::I=10000, tol::R=1e-4,
                     adaptive::Bool=false, fast::Bool=false, verbose::I=1, verbose_freq::I = 100,
                     cq = Float64, cs = Float64 # default type of codomain of As and Aq
                     ) where {I, R, D, FS, AS, FQ, AQ, G}
    mq = size(Aq, 1)
    ms = size(As, 1)
    x = blockcopy(x0)
    y = blockzeros(x0)
    z = blockzeros(x0)
    z_prev = blockzeros(x0)
    FPR_x = blockzeros(x0)
    Aqx = blockzeros(cq, mq)
    Asx = blockzeros(cs, ms)
    Aqz = blockzeros(cq, mq)
    Asz = blockzeros(cs, ms)
    gradfq_Aqx = blockzeros(cq, mq)
    gradfs_Asx = blockzeros(cs, ms)
    Aqt_gradfq_Aqx = blockzeros(x0)
    Ast_gradfs_Asx = blockzeros(x0)
    At_gradf_Ax = blockzeros(x0)
    Aqz_prev = blockzeros(cq, mq)
    Asz_prev = blockzeros(cs, ms)
    gradfq_Aqz = blockzeros(cq, mq)
    gradfs_Asz = blockzeros(cs, ms)
    gradfq_Aqz_prev = blockzeros(cq, mq)
    diff_gradfq_Aqx = blockzeros(cq, mq)
    diff_Aqx = blockzeros(cq, mq)
    Cq = typeof(Aqx)
    Cs = typeof(Asx)
    FBSIterator{I, R, D, Cs, Cq, FS, AS, FQ, AQ, G}(x,
                         fs, As, fq, Aq, g,
                         gamma, maxit, tol, adaptive, fast, verbose, verbose_freq, 1.0,
                         y, z, z_prev, FPR_x,
                         Aqx, Asx,
                         Aqz, Asz,
                         gradfq_Aqx, gradfs_Asx,
                         Aqt_gradfq_Aqx, Ast_gradfs_Asx,
                         0.0, 0.0, 0.0,
                         At_gradf_Ax, Aqz_prev,
                         Asz_prev,
                         gradfq_Aqz, gradfs_Asz, gradfq_Aqz_prev, diff_gradfq_Aqx, diff_Aqx)
end
```

unfortunately -talking about dependencies- it looks like `blockzeros` needs a slight modification since it is not working with the call  `blockzeros(::DataType,::Int)`

**Comment by nantonel** [comment]
or even more simpler, without introducing new keyword arguments, we simply do:
```julia
Aqx = Aq*x0
Asx = As*x0
Aqz = blockzeros(Aqx)
Asz = blockzeros(Asx)
....
Cq = typeof(Aqx)
Cs = typeof(Asx)
```
